default:
    controller: App\Controller\MainController
    method: index
    params: { routine_id: int }
privacy:
    controller: App\Controller\MainController
    method: privacy
terms:
    controller: App\Controller\MainController
    method: terms
contact:
    controller: App\Controller\MainController
    method: contact
create_new_exercise:
    controller: App\Controller\MainController
    method: createNewExercise
register:
    controller: App\Controller\MainController
    method: register
login:
    controller: App\Controller\MainController
    method: login
logout:
    controller: App\Controller\MainController
    method: logout
delete_account:
    controller: App\Controller\MainController
    method: deleteAccount
ajax_set_theme:
    controller: App\Controller\MainController
    method: ajaxSetTheme
    params: { theme: string }
ajax_save_routine_order:
    controller: App\Controller\MainController
    method: ajaxSaveRoutineOrder
    params: { routine_id: int, items: array }
ajax_edit_routine:
    controller: App\Controller\MainController
    method: ajaxEditRoutine
    params: { routine_id: int, name: string }
ajax_delete_routine:
    controller: App\Controller\MainController
    method: ajaxDeleteRoutine
    params: { routine_id: int }
ajax_delete_exercise:
    controller: App\Controller\MainController
    method: ajaxDeleteExercise
    params: { exercise_id: int }
ajax_save_account:
    controller: App\Controller\MainController
    method: ajaxSaveAccount
    params: { name: string, email: string, password: string }
ajax_change_exercise:
    controller: App\Controller\MainController
    method: ajaxChangeExercise
    params: { exercise_id: int, routine_id: int }
ajax_edit_exercise:
    controller: App\Controller\MainController
    method: ajaxEditExercise
    params: { id: int, name: string, routine_id: int }
ajax_heart_routine:
    controller: App\Controller\MainController
    method: ajaxHeartRoutine
    params: { routine_id: int, items: array, limit: int, set_length: int, set_break: int, rounds: int }
ajax_unheart_routine:
    controller: App\Controller\MainController
    method: ajaxUnHeartRoutine
    params: { routine_id: int }
account:
    controller: App\Controller\MainController
    method: account
    params: { routine_id: int }
