name: Prod Deploy
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v2.3.2
      
    - name: Install SSH
      run:
        sudo apt-get update
        sudo apt-get install openssh-client -y
          
    - name: Deploy to server
      run:
        sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.SERVER }} 'cd public_html && composer install && composer update && git pull && vendor/bin/phinx migrate'
